name: Python Analysis Workflow

on:
  push:
    branches:
      - develop
      - master
      - hotfix/*
      - feature/*
    tags:
  pull_request:

jobs:
  setup:
    name: Setup Conda Env
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: refuse-base
          environment-file: ../etc/refuse-base-env.conda
          auto-activate-base: false

