name: Python Analysis Workflow

on:
  push:
    branches:
      - develop
      - master
      - hotfix/*
      - feature/*
    tags:
  pull_request:

jobs:
  setup:
    name: Python Analysis Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Conda Env
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: refuse-env
          environment-file: etc/refuse-env.yml
          auto-activate-base: false
      - run: conda list
      - name: Linter
        run: bash run_pylint.sh

