name: Static Python Check | master

on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  setup:
    name: Python Analysis Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1.0.7

      - name: Activate Conda Env
        run: conda env update --file etc/refuse-env.yml --name base

      - name: Linter
        run: bash run_pylint.sh

      - name: Type Checker
        run: bash run_mypy.sh

