name: Python Analysis Workflow

on:
  push:
    branches:
      - develop
      - master
      - hotfix/*
      - feature/*
    tags:
  pull_request:

jobs:
  setup:
    name: Setup Conda Env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: refuse-env
          environment-file: etc/refuse-env.yml
          auto-activate-base: false
  linter:
    name: Python Linter
    runs-on: ubuntu-latest
    steps:
      -run: bash run_pylint.sh

